services:

  db:
    container_name: centerlog_db
    image: "postgres:16"
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_PORT: ${DB_PORT}
      PGDATA: /var/lib/postgresql/data/pgdata
    shm_size: '256m' # Necessary to use Postgres VACUUM. You can increment it as you need
    volumes:
      - /temp/db/:/var/lib/postgresql/data/
    networks:
      - centerlog
    ports:
      - "${DB_PORT}:5432"

    

  server:
    build: ./server
    container_name: centerlog_server
    #image:
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_LISTEN: http://0.0.0.0:9200
    networks:
      - centerlog
      #- your-network
    ports:
      - 9200:9200

  client:
    container_name: centerlog_client
    #image:
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - server
    networks:
      - centerlog
      #- your-network


networks:
  centerlog:
    driver: bridge