services:

  db:
    container_name: centerlog_db
    image: "postgres:16"
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_PORT: ${DB_PORT}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /temp/db/:/var/lib/postgresql/data/
    networks:
      - centerlog
    ports:
      - "${DB_PORT}:5432"
    mem_limit: 256m
    cpus: 1           # Limita o uso a 2 CPUs

    

  server:
    build: ./server
    container_name: centerlog_server
    #image:
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      ASPNETCORE_ENVIRONMENT: Production
    networks:
      - centerlog
      #- your-network
    ports:
      - 5000:5000

  client:
    container_name: centerlog_client
    #image:
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
    #volumes:
    #  - "./appsettings-front.json:/app/src/appsettings.json"
    ports:
      - "5173:5173"
    depends_on:
      - server
    networks:
      - centerlog
      #- your-network


networks:
  centerlog:
    driver: bridge