services:

  db:
    container_name: centerlog_db
    image: "postgres:16"
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_PORT: ${DB_PORT}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./db/:/var/lib/postgresql/data/
    networks:
      - centerlog
    ports:
      - "5435:5432"
    mem_limit: 512m
    

  server:
    build: ./server
    container_name: centerlog_server
    #image:
    restart: always
    environment:
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - centerlog
    ports:
      - 5000:5000



networks:
  centerlog:
    driver: bridge